In [1]:
import torch
import torchvision
from torchvision import transforms

In [2]:
torchvision

<module 'torchvision' from '/Users/rio/opt/anaconda3/lib/python3.9/site-packages/torchvision/__init__.py'>

In [6]:
torchvision.datasets.CIFAR10.train_list[0]

['data_batch_1', 'c99cafc152244af753f735de768cd75f']

In [11]:
torch.Tensor([1, 2]).fill_(7)

tensor([7., 7.])

In [13]:
torch.rand(4, 4)

tensor([[0.3707, 0.7904, 0.5344, 0.3271],
        [0.5213, 0.3682, 0.0776, 0.4786],
        [0.4203, 0.2554, 0.6303, 0.6255],
        [0.9297, 0.0960, 0.1669, 0.3877]])

In [17]:
torch.randperm(5)

tensor([1, 0, 4, 3, 2])

In [19]:
import numpy as np

In [20]:
torch.from_numpy(np.arange(9))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
torch.matmul(torch.Tensor([1,2]), torch.Tensor([4,3]))

tensor(10.)

In [28]:
transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize(
         (0.5, 0.5, 0.5),
         (0.5, 0.5, 0.5)
     )
    ]
)
transform

Compose(
    ToTensor()
    Normalize(mean=(0.5, 0.5, 0.5), std=(0.5, 0.5, 0.5))
)

In [29]:
batch_size = 4

In [1]:
import os, sys
# trainset = 
train_path = "../harry potters/"
# os.pardir(train_path)
# os.path.abspath(train_path)
# sys.path
from PIL import Image
import glob
image_list = []
# for filename in glob.glob('yourpath/*.gif'): #assuming gif
# for filename in glob.glob(os.path.abspath(train_path)): #assuming gif
for filename in glob.glob(os.path.join(train_path, '*')): #assuming gif
    # im = Image.open(filename)
    # image_list.append(im)
    print(filename)

../harry potters/2100.jpg
../harry potters/1421.jpg
../harry potters/3550.jpg
../harry potters/5860.jpg
../harry potters/610.jpg
../harry potters/6731.66494288_220X220.jpg
../harry potters/6170.jpg
../harry potters/5451.jpg
../harry potters/1151.jpg
../harry potters/7252.jpg
../harry potters/3961.jpg
../harry potters/8820.jpg
../harry potters/360.jpg
../harry potters/6831.jpg
../harry potters/3791.jpg
../harry potters/2510.jpg
../harry potters/8001.jpg
../harry potters/4650.jpeg.pagespeed.ic.Mr3qqrOaAL.jpg
../harry potters/1970.jpg
../harry potters/1780.jpg
../harry potters/1794.jpg
../harry potters/9492.png
../harry potters/2712.jpg
../harry potters/4411.jpg
../harry potters/2060.jpg
../harry potters/6560.jpg
../harry potters/1541.jpg
../harry potters/7865.jpg
../harry potters/980.jpg
../harry potters/770.jpg
../harry potters/5082.jpg
../harry potters/3380.jpg
../harry potters/7680.jpg
../harry potters/1583.jpg
../harry potters/1232.jpg
../harry potters/8202.jpg
../harry potters/1540.

In [ ]:
image_list